### ISSUE TITLE
Broken doc

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/HighSpeedConverterToolbox#87]
This page:
https://analogdevicesinc.github.io/HighSpeedConverterToolbox/master/models/

includes a link to this:
https://analogdevicesinc.github.io/models/ad9081/top_level.tex/

which is a 404

should be:
https://analogdevicesinc.github.io/HighSpeedConverterToolbox/master/models/ad9081/top_level.tex/

or something like that...

-Robin

**Comment by tfcollins** [comment]
Should be fixed now: https://github.com/analogdevicesinc/HighSpeedConverterToolbox/pull/88
